import Drop from "@assets/ConcernsWidget/Drop.svg";
import Graph from "@assets/ConcernsWidget/Graph.svg";
import {
	AtrialFibrillationPlanMockData,
	CoronaryArteryDiseasePlanMockData,
	HeartFailurePlanMockData,
	HypertensionPlanMockData,
	planMockData,
	PlanSection,
	StrokePlanMockData,
} from "../../PlanWidget/helpers/planMockData";

export interface Detail {
	id: number;
	title: string;
	factors: string[];
	reasons: Reason[];
	symptoms?: Symptoms;
	plan: PlanSection[];
	status: "High" | "Medium" | "Low";
	frame?: string;
	description?: string[];
}

export interface Reason {
	id: number;
	title: string;
	icon: string;
	test: string;
	level: { type: "progress"; src: number } | { type: "image"; src: string };
	value: string;
	unit: string;
	statusText: string;
	status: "High" | "Medium" | "Low";
	description: string;
	date: string;
}

export interface Symptoms {
	id: number;
	description: string;
	symptomsList: string[];
}

export interface SystemConcerns {
	id: number;
	title: string;
	details: Detail[];
	defaultPlan: PlanSection[];
}

export const detailedSystemConcerns: SystemConcerns[] = [
	{
		id: 1,
		title: "systemConcerns.cardiovascular.title",
		defaultPlan: planMockData,
		details: [
			{
				id: 1,
				title: "details.atrialFibrillation.title",
				factors: [
					"details.atrialFibrillation.factors.highCholesterol",
					"details.atrialFibrillation.factors.otherFactors",
				],
				status: "High",
				reasons: [
					{
						id: 1,
						title: "reasons.ldl.title",
						icon: Drop,
						test: "reasons.ldl.test",
						level: { type: "progress", src: 55 },
						value: "112",
						unit: "reasons.ldl.unit",
						statusText: "reasons.ldl.statusText",
						status: "High",
						description: "reasons.ldl.description",
						date: "100-129",
					},
					{
						id: 2,
						title: "reasons.vldl.title",
						icon: Drop,
						test: "reasons.vldl.test",
						level: { type: "image", src: Graph },
						value: "17",
						unit: "reasons.vldl.unit",
						statusText: "reasons.vldl.statusText",
						status: "Low",
						description: "reasons.vldl.description",
						date: "7-40",
					},
					{
						id: 3,
						title: "reasons.hdl.title",
						icon: Drop,
						test: "reasons.hdl.test",
						level: { type: "progress", src: 0 },
						value: "58",
						unit: "reasons.hdl.unit",
						statusText: "reasons.hdl.statusText",
						status: "High",
						description: "reasons.hdl.description",
						date: "60-null",
					},
					{
						id: 4,
						title: "reasons.cholesterol.title",
						icon: Drop,
						test: "reasons.cholesterol.test",
						level: { type: "progress", src: 55 },
						value: "181",
						unit: "reasons.cholesterol.unit",
						statusText: "reasons.cholesterol.statusText",
						status: "Low",
						description: "reasons.cholesterol.description",
						date: "null-200",
					},
					{
						id: 5,
						title: "reasons.cholesterolHdl.title",
						icon: Drop,
						test: "reasons.cholesterolHdl.test",
						level: { type: "progress", src: 50 },
						value: "3.1",
						unit: "reasons.cholesterolHdl.unit",
						statusText: "reasons.cholesterolHdl.statusText",
						status: "Low",
						description: "reasons.cholesterolHdl.description",
						date: "null-4",
					},
					{
						id: 6,
						title: "reasons.hba1c.title",
						icon: Drop,
						test: "reasons.hba1c.test",
						level: { type: "progress", src: 55 },
						value: "5.3",
						unit: "reasons.hba1c.unit",
						statusText: "reasons.hba1c.statusText",
						status: "Low",
						description: "reasons.hba1c.description",
						date: "4-6",
					},
				],
				symptoms: {
					id: 1,
					description: "symptoms.atrialFibrillation.description",
					symptomsList: [
						"symptoms.atrialFibrillation.palpitations",
						"symptoms.atrialFibrillation.shortnessOfBreath",
						"symptoms.atrialFibrillation.fatigue",
						"symptoms.atrialFibrillation.chestPain",
						"symptoms.atrialFibrillation.dizziness",
						"symptoms.atrialFibrillation.weakness",
					],
				},
				plan: AtrialFibrillationPlanMockData,
				frame:
					"https://human.biodigital.com/viewer/?id=5v3G&ui-anatomy-descriptions=true&ui-anatomy-pronunciations=true&ui-anatomy-labels=false&ui-audio=true&ui-chapter-list=false&ui-fullscreen=false&ui-help=false&ui-info=false&ui-label-list=true&ui-layers=false&ui-skin-layers=false&ui-loader=circle&ui-media-controls=none&ui-menu=false&ui-nav=false&ui-search=false&ui-tools=false&ui-tutorial=false&ui-undo=false&ui-whiteboard=false&initial.none=true&disable-scroll=false&dk=57a9053995a029ade6a11d83c8a64a4fedef2b19&paid=o_27f525a0",
				description: [
					"details.atrialFibrillation.description.0",
					"details.atrialFibrillation.description.1",
					"details.atrialFibrillation.description.2",
				],
			},
			{
				id: 2,
				title: "details.stroke.title",
				factors: [
					"details.stroke.factors.highHeartRate",
					"details.stroke.factors.otherFactors",
				],
				status: "High",
				reasons: [
					{
						id: 1,
						title: "reasons.ldl.title",
						icon: Drop,
						test: "reasons.ldl.test",
						level: { type: "progress", src: 55 },
						value: "112",
						unit: "reasons.ldl.unit",
						statusText: "reasons.ldl.statusText",
						status: "High",
						description: "reasons.ldl.description",
						date: "100-129",
					},
					{
						id: 2,
						title: "reasons.vldl.title",
						icon: Drop,
						test: "reasons.vldl.test",
						level: { type: "progress", src: 55 },
						value: "17",
						unit: "reasons.vldl.unit",
						statusText: "reasons.vldl.statusText",
						status: "Low",
						description: "reasons.vldl.description",
						date: "7-40",
					},
					{
						id: 3,
						title: "reasons.hdl.title",
						icon: Drop,
						test: "reasons.hdl.test",
						level: { type: "image", src: Graph },
						value: "58",
						unit: "reasons.hdl.unit",
						statusText: "reasons.hdl.statusText",
						status: "Medium",
						description: "reasons.hdl.description",
						date: "60-null",
					},
					{
						id: 4,
						title: "reasons.cholesterol.title",
						icon: Drop,
						test: "reasons.cholesterol.test",
						level: { type: "progress", src: 35 },
						value: "181",
						unit: "reasons.cholesterol.unit",
						statusText: "reasons.cholesterol.statusText",
						status: "Low",
						description: "reasons.cholesterol.description",
						date: "null-200",
					},
					{
						id: 5,
						title: "reasons.cholesterolHdl.title",
						icon: Drop,
						test: "reasons.cholesterolHdl.test",
						level: { type: "progress", src: 50 },
						value: "3.1",
						unit: "reasons.cholesterolHdl.unit",
						statusText: "reasons.cholesterolHdl.statusText",
						status: "Low",
						description: "reasons.cholesterolHdl.description",
						date: "null-4",
					},
					{
						id: 6,
						title: "reasons.hba1c.title",
						icon: Drop,
						test: "reasons.hba1c.test",
						level: { type: "image", src: Graph },
						value: "5.3",
						unit: "reasons.hba1c.unit",
						statusText: "reasons.hba1c.statusText",
						status: "Low",
						description: "reasons.hba1c.description",
						date: "4-6",
					},
				],
				symptoms: {
					id: 1,
					description: "symptoms.stroke.description",
					symptomsList: [
						"symptoms.stroke.numbness",
						"symptoms.stroke.confusion",
						"symptoms.stroke.visionProblems",
						"symptoms.stroke.walkingDifficulty",
						"symptoms.stroke.severeHeadache",
					],
				},
				plan: StrokePlanMockData,
				frame:
					"https://human.biodigital.com/viewer/?id=5v3G&ui-anatomy-descriptions=true&ui-anatomy-pronunciations=true&ui-anatomy-labels=false&ui-audio=true&ui-chapter-list=false&ui-fullscreen=false&ui-help=false&ui-info=false&ui-label-list=true&ui-layers=false&ui-skin-layers=false&ui-loader=circle&ui-media-controls=none&ui-menu=false&ui-nav=false&ui-search=false&ui-tools=false&ui-tutorial=false&ui-undo=false&ui-whiteboard=false&initial.none=true&disable-scroll=false&dk=57a9053995a029ade6a11d83c8a64a4fedef2b19&paid=o_27f525a0",
			},
			{
				id: 3,
				title: "details.coronaryArteryDisease.title",
				factors: [
					"details.coronaryArteryDisease.factors.highHeartRate",
					"details.coronaryArteryDisease.factors.otherFactors",
				],
				status: "Medium",
				reasons: [
					{
						id: 1,
						title: "reasons.ldl.title",
						icon: Drop,
						test: "reasons.ldl.test",
						level: { type: "progress", src: 51 },
						value: "112",
						unit: "reasons.ldl.unit",
						statusText: "reasons.ldl.statusText",
						status: "High",
						description: "reasons.ldl.description",
						date: "100-129",
					},
					{
						id: 2,
						title: "reasons.vldl.title",
						icon: Drop,
						test: "reasons.vldl.test",
						level: { type: "progress", src: 43 },
						value: "17",
						unit: "reasons.vldl.unit",
						statusText: "reasons.vldl.statusText",
						status: "Low",
						description: "reasons.vldl.description",
						date: "7-40",
					},
					{
						id: 3,
						title: "reasons.hdl.title",
						icon: Drop,
						test: "reasons.hdl.test",
						level: { type: "progress", src: 85 },
						value: "58",
						unit: "reasons.hdl.unit",
						statusText: "reasons.hdl.statusText",
						status: "Medium",
						description: "reasons.hdl.description",
						date: "60-null",
					},
					{
						id: 4,
						title: "reasons.cholesterol.title",
						icon: Drop,
						test: "reasons.cholesterol.test",
						level: { type: "progress", src: 55 },
						value: "181",
						unit: "reasons.cholesterol.unit",
						statusText: "reasons.cholesterol.statusText",
						status: "Low",
						description: "reasons.cholesterol.description",
						date: "null-200",
					},
					{
						id: 5,
						title: "reasons.cholesterolHdl.title",
						icon: Drop,
						test: "reasons.cholesterolHdl.test",
						level: { type: "image", src: Graph },
						value: "3.1",
						unit: "reasons.cholesterolHdl.unit",
						statusText: "reasons.cholesterolHdl.statusText",
						status: "Low",
						description: "reasons.cholesterolHdl.description",
						date: "null-4",
					},
					{
						id: 6,
						title: "reasons.hba1c.title",
						icon: Drop,
						test: "reasons.hba1c.test",
						level: { type: "progress", src: 15 },
						value: "5.3",
						unit: "reasons.hba1c.unit",
						statusText: "reasons.hba1c.statusText",
						status: "Low",
						description: "reasons.hba1c.description",
						date: "4-6",
					},
				],
				symptoms: {
					id: 1,
					description: "symptoms.coronaryArteryDisease.description",
					symptomsList: [
						"symptoms.coronaryArteryDisease.chestPain",
						"symptoms.coronaryArteryDisease.shortnessOfBreath",
						"symptoms.coronaryArteryDisease.fatigue",
						"symptoms.coronaryArteryDisease.palpitations",
						"symptoms.coronaryArteryDisease.nausea",
					],
				},
				plan: CoronaryArteryDiseasePlanMockData,
				frame:
					"https://human.biodigital.com/viewer/?id=5v3G&ui-anatomy-descriptions=true&ui-anatomy-pronunciations=true&ui-anatomy-labels=false&ui-audio=true&ui-chapter-list=false&ui-fullscreen=false&ui-help=false&ui-info=false&ui-label-list=true&ui-layers=false&ui-skin-layers=false&ui-loader=circle&ui-media-controls=none&ui-menu=false&ui-nav=false&ui-search=false&ui-tools=false&ui-tutorial=false&ui-undo=false&ui-whiteboard=false&initial.none=true&disable-scroll=false&dk=57a9053995a029ade6a11d83c8a64a4fedef2b19&paid=o_27f525a0",
			},
			{
				id: 4,
				title: "details.hypertension.title",
				factors: [
					"details.hypertension.factors.highCholesterol",
					"details.hypertension.factors.otherFactors",
				],
				status: "High",
				reasons: [
					{
						id: 1,
						title: "reasons.ldl.title",
						icon: Drop,
						test: "reasons.ldl.test",
						level: { type: "progress", src: 15 },
						value: "112",
						unit: "reasons.ldl.unit",
						statusText: "reasons.ldl.statusText",
						status: "High",
						description: "reasons.ldl.description",
						date: "100-129",
					},
					{
						id: 2,
						title: "reasons.vldl.title",
						icon: Drop,
						test: "reasons.vldl.test",
						level: { type: "progress", src: 50 },
						value: "17",
						unit: "reasons.vldl.unit",
						statusText: "reasons.vldl.statusText",
						status: "Low",
						description: "reasons.vldl.description",
						date: "7-40",
					},
					{
						id: 3,
						title: "reasons.hdl.title",
						icon: Drop,
						test: "reasons.hdl.test",
						level: { type: "progress", src: 75 },
						value: "58",
						unit: "reasons.hdl.unit",
						statusText: "reasons.hdl.statusText",
						status: "Medium",
						description: "reasons.hdl.description",
						date: "60-null",
					},
					{
						id: 4,
						title: "reasons.cholesterol.title",
						icon: Drop,
						test: "reasons.cholesterol.test",
						level: { type: "progress", src: 35 },
						value: "181",
						unit: "reasons.cholesterol.unit",
						statusText: "reasons.cholesterol.statusText",
						status: "Low",
						description: "reasons.cholesterol.description",
						date: "null-200",
					},
					{
						id: 5,
						title: "reasons.cholesterolHdl.title",
						icon: Drop,
						test: "reasons.cholesterolHdl.test",
						level: { type: "image", src: Graph },
						value: "3.1",
						unit: "reasons.cholesterolHdl.unit",
						statusText: "reasons.cholesterolHdl.statusText",
						status: "Low",
						description: "reasons.cholesterolHdl.description",
						date: "null-4",
					},
					{
						id: 6,
						title: "reasons.hba1c.title",
						icon: Drop,
						test: "reasons.hba1c.test",
						level: { type: "progress", src: 25 },
						value: "5.3",
						unit: "reasons.hba1c.unit",
						statusText: "reasons.hba1c.statusText",
						status: "Low",
						description: "reasons.hba1c.description",
						date: "4-6",
					},
				],
				symptoms: {
					id: 1,
					description: "symptoms.hypertension.description",
					symptomsList: [
						"symptoms.hypertension.headaches",
						"symptoms.hypertension.shortnessOfBreath",
						"symptoms.hypertension.nosebleeds",
						"symptoms.hypertension.fatigue",
						"symptoms.hypertension.visionProblems",
					],
				},
				plan: HypertensionPlanMockData,
				frame:
					"https://human.biodigital.com/viewer/?id=5v3G&ui-anatomy-descriptions=true&ui-anatomy-pronunciations=true&ui-anatomy-labels=false&ui-audio=true&ui-chapter-list=false&ui-fullscreen=false&ui-help=false&ui-info=false&ui-label-list=true&ui-layers=false&ui-skin-layers=false&ui-loader=circle&ui-media-controls=none&ui-menu=false&ui-nav=false&ui-search=false&ui-tools=false&ui-tutorial=false&ui-undo=false&ui-whiteboard=false&initial.none=true&disable-scroll=false&dk=57a9053995a029ade6a11d83c8a64a4fedef2b19&paid=o_27f525a0",
			},
			{
				id: 5,
				title: "details.heartFailure.title",
				factors: [
					"details.heartFailure.factors.highHeartRate",
					"details.heartFailure.factors.otherFactors",
				],
				status: "Low",
				reasons: [
					{
						id: 1,
						title: "reasons.ldl.title",
						icon: Drop,
						test: "reasons.ldl.test",
						level: { type: "progress", src: 55 },
						value: "112",
						unit: "reasons.ldl.unit",
						statusText: "reasons.ldl.statusText",
						status: "Medium",
						description: "reasons.ldl.description",
						date: "100-129",
					},
					{
						id: 2,
						title: "reasons.vldl.title",
						icon: Drop,
						test: "reasons.vldl.test",
						level: { type: "progress", src: 55 },
						value: "17",
						unit: "reasons.vldl.unit",
						statusText: "reasons.vldl.statusText",
						status: "Low",
						description: "reasons.vldl.description",
						date: "7-40",
					},
					{
						id: 3,
						title: "reasons.hdl.title",
						icon: Drop,
						test: "reasons.hdl.test",
						level: { type: "progress", src: 15 },
						value: "58",
						unit: "reasons.hdl.unit",
						statusText: "reasons.hdl.statusText",
						status: "High",
						description: "reasons.hdl.description",
						date: "60-null",
					},
					{
						id: 4,
						title: "reasons.cholesterol.title",
						icon: Drop,
						test: "reasons.cholesterol.test",
						level: { type: "progress", src: 55 },
						value: "181",
						unit: "reasons.cholesterol.unit",
						statusText: "reasons.cholesterol.statusText",
						status: "Low",
						description: "reasons.cholesterol.description",
						date: "null-200",
					},
					{
						id: 5,
						title: "reasons.cholesterolHdl.title",
						icon: Drop,
						test: "reasons.cholesterolHdl.test",
						level: { type: "image", src: Graph },
						value: "3.1",
						unit: "reasons.cholesterolHdl.unit",
						statusText: "reasons.cholesterolHdl.statusText",
						status: "Low",
						description: "reasons.cholesterolHdl.description",
						date: "null-4",
					},
					{
						id: 6,
						title: "reasons.hba1c.title",
						icon: Drop,
						test: "reasons.hba1c.test",
						level: { type: "progress", src: 85 },
						value: "5.3",
						unit: "reasons.hba1c.unit",
						statusText: "reasons.hba1c.statusText",
						status: "Low",
						description: "reasons.hba1c.description",
						date: "4-6",
					},
				],
				symptoms: {
					id: 1,
					description: "symptoms.heartFailure.description",
					symptomsList: [
						"symptoms.heartFailure.suddenCollapse",
						"symptoms.heartFailure.noPulse",
						"symptoms.heartFailure.noBreathing",
						"symptoms.heartFailure.lossOfConsciousness",
						"symptoms.heartFailure.precedingSymptoms",
					],
				},
				plan: HeartFailurePlanMockData,
				frame:
					"https://human.biodigital.com/viewer/?id=5v3G&ui-anatomy-descriptions=true&ui-anatomy-pronunciations=true&ui-anatomy-labels=false&ui-audio=true&ui-chapter-list=false&ui-fullscreen=false&ui-help=false&ui-info=false&ui-label-list=true&ui-layers=false&ui-skin-layers=false&ui-loader=circle&ui-media-controls=none&ui-menu=false&ui-nav=false&ui-search=false&ui-tools=false&ui-tutorial=false&ui-undo=false&ui-whiteboard=false&initial.none=true&disable-scroll=false&dk=57a9053995a029ade6a11d83c8a64a4fedef2b19&paid=o_27f525a0",
			},
		],
	},
];
